version: '3.8'

networks:
  kafka-net:
    driver: bridge

services:
  TEST-ZOOKEEPER:
    image: confluentinc/cp-zookeeper:latest
    container_name: TEST-ZOOKEEPER
    networks:
      - kafka-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 9000
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "9000:9000"
    volumes:
      - /Users/hyungjun/Volumes/zookeeper-data:/var/lib/zookeeper

  TEST-KAFKA01:
    image: confluentinc/cp-kafka:latest
    container_name: TEST-KAFKA01
    networks:
      - kafka-net
    depends_on:
      - TEST-ZOOKEEPER
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: TEST-ZOOKEEPER:9000
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9001,PLAINTEXT_INTERNAL://TEST-KAFKA01:19001
      KAFKA_LISTENERS: PLAINTEXT://:9001,PLAINTEXT_INTERNAL://:19001
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
    ports:
      - "9001:9001"
    volumes:
      - /Users/hyungjun/Volumes/kafka1-data:/var/lib/kafka/data

  TEST-KAFKA02:
    image: confluentinc/cp-kafka:latest
    container_name: TEST-KAFKA02
    networks:
      - kafka-net
    depends_on:
      - TEST-ZOOKEEPER
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: TEST-ZOOKEEPER:9000
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9002,PLAINTEXT_INTERNAL://TEST-KAFKA02:19002
      KAFKA_LISTENERS: PLAINTEXT://:9002,PLAINTEXT_INTERNAL://:19002
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
    ports:
      - "9002:9002"
    volumes:
      - /Users/hyungjun/Volumes/kafka2-data:/var/lib/kafka/data